Algoritmo "Função 3"
// Criar uma função para calcular o dobro de um numero passado como parametro;
Var

   numero, resultado: real


funcao Dobro (valor: real) : real

var

   total:real

inicio
      total <- valor *2
      retorne total
fimfuncao



Inicio
   escreval ("Digite um numero para calcular o dobro: ")
   leia (numero)
   resultado <- Dobro (numero)
   escreva (" O dobro é : ", resultado)


Fimalgoritmo